// File generated by FlutterFire CLI or placeholder for Mess Manager app.
// Update these fields with your Firebase project configurations or run:
// `flutterfire configure`
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf9HOWf2jufxbVuEmTo0bVZPrIiT5tszc',
    appId: '1:195079922161:web:e5c67cd061c92adeb6e450',
    messagingSenderId: '195079922161',
    projectId: 'messmanager-95869',
    authDomain: 'messmanager-95869.firebaseapp.com',
    databaseURL: 'https://messmanager-95869-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'messmanager-95869.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARQUuoVTAh73uW_taZBfuGSnyUy0cxeds',
    appId: '1:195079922161:android:9f91c232a447c63cb6e450',
    messagingSenderId: '195079922161',
    projectId: 'messmanager-95869',
    databaseURL: 'https://messmanager-95869-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'messmanager-95869.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdJD_kdPV1lVa5OLmXkxcCJcGW3ic18vI',
    appId: '1:195079922161:ios:5f00a6f878d23bd8b6e450',
    messagingSenderId: '195079922161',
    projectId: 'messmanager-95869',
    databaseURL: 'https://messmanager-95869-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'messmanager-95869.firebasestorage.app',
    iosBundleId: 'com.example.messManager',
  );
}
